name: CI

on: 
  pull_request:
    branches:
      - master
    types: closed

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
    
      - uses: actions/checkout@v2
      - name: Get Previous Tag
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
      - name: Generate Tag
        id: generate-tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: sh scripts/release.sh ${{ steps.previoustag.outputs.tag }}
      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.generate-tag.outputs.version }}
          release_name: Release ${{ steps.generate-tag.outputs.version }}
          prerelease: false

    # - name: upload release
    #   uses: actions/upload-release-asset@v1.0.2
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     upload_url: ${{ steps.create-release.outputs.upload_url }}
    #     asset_path: 
    #     asset_name:
    #     asset_content_type: